# Copyright Contributors to the Open Cluster Management project

kind: Deployment
apiVersion: apps/v1
metadata:
  name: clusterlifecycle-state-metrics
  namespace: open-cluster-management
spec:
  template:
    spec:
      containers:
      - name: clusterlifecycle-state-metrics
        image: REPLACE_IMAGE
        volumeMounts:
          - mountPath: "/var/run/clusterlifecycle-state-metrics"
            name: certs
            readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: clusterlifecycle-state-metrics-certs